version: "3.7"
services:
  redis:
    image: redis:7.2-alpine
    container_name: newton-redis
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass bangsoal
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  database:
    image: postgres:13.4-alpine
    container_name: newton-postgres
    ports:
      - 5433:5432  # Port host:Port container (WAJIB 5433 karena 5432 sudah dipakai)
    environment:
      POSTGRES_PASSWORD: bangsoal2024
      POSTGRES_USER: bangsoal
      POSTGRES_DB: bs_db
      